-- Aqua Sentinel Supabase Schema with RPC Security Layer

-- 1. Create the Devices Table (Hardware Inventory)
CREATE TABLE IF NOT EXISTS public.devices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    device_secret TEXT NOT NULL,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the Telemetry Table (If starting fresh)
CREATE TABLE IF NOT EXISTS public.water_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    device_id UUID REFERENCES public.devices(id),
    water_level_cm NUMERIC,
    tds_ppm NUMERIC,
    turbidity_ntu NUMERIC
);

-- 2b. If you already created the table previously, this ensures the device_id column is properly linked
ALTER TABLE public.water_data ADD COLUMN IF NOT EXISTS device_id UUID REFERENCES public.devices(id);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.water_data ENABLE ROW LEVEL SECURITY;

-- 4. Clean up old V1.0 policies so you don't get "Policy Already Exists" errors
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow anonymous reads" ON public.water_data;
    DROP POLICY IF EXISTS "Allow anonymous inserts" ON public.water_data;
END
$$;

-- Allow public reading of data (for your frontend web dashboard)
CREATE POLICY "Allow anonymous reads" ON public.water_data FOR SELECT TO anon USING (true);

-- NOTICE: We do NOT recreate the INSERT policy for anon. 
-- Direct database inserts from the internet are now completely blocked.

-- 5. Secure RPC Function (The Bouncer)
CREATE OR REPLACE FUNCTION log_telemetry(
    p_device_id UUID,
    p_device_secret TEXT,
    p_water_level_cm NUMERIC,
    p_tds_ppm NUMERIC,
    p_turbidity_ntu NUMERIC
) RETURNS BOOLEAN AS $$
DECLARE
    valid_device BOOLEAN;
BEGIN
    -- Check if the device ID and secret match exactly in the devices table
    SELECT EXISTS (
        SELECT 1 FROM public.devices 
        WHERE id = p_device_id AND device_secret = p_device_secret
    ) INTO valid_device;

    -- If valid, insert the data. 
    -- (SECURITY DEFINER allows this function to bypass the RLS block we set above)
    IF valid_device THEN
        INSERT INTO public.water_data (device_id, water_level_cm, tds_ppm, turbidity_ntu)
        VALUES (p_device_id, p_water_level_cm, p_tds_ppm, p_turbidity_ntu);
        RETURN TRUE;
    ELSE
        -- If invalid, reject the payload and trigger an error
        RAISE EXCEPTION 'Unauthorized: Invalid Device ID or Secret';
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
